CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

CREATE TABLE "Employees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeCode" character varying(20) NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" text NOT NULL,
    "PhoneNumber" character varying(20),
    "DepartmentId" integer NOT NULL,
    "Role" integer NOT NULL,
    "ManagerId" integer,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Employees_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Employees_Employees_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AttendanceLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "CheckInTime" timestamp with time zone,
    "CheckOutTime" timestamp with time zone,
    "WorkDate" date NOT NULL,
    "Status" integer NOT NULL,
    "DeviceType" integer NOT NULL,
    CONSTRAINT "PK_AttendanceLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AttendanceLogs_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

CREATE TABLE "LeaveRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "LeaveType" integer NOT NULL,
    "StartDate" date NOT NULL,
    "EndDate" date NOT NULL,
    "Reason" character varying(500),
    "Status" integer NOT NULL,
    "ApprovedById" integer,
    "AppliedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaveRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LeaveRequests_Employees_ApprovedById" FOREIGN KEY ("ApprovedById") REFERENCES "Employees" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_LeaveRequests_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_AttendanceLogs_EmployeeId_WorkDate" ON "AttendanceLogs" ("EmployeeId", "WorkDate");

CREATE INDEX "IX_AttendanceLogs_WorkDate" ON "AttendanceLogs" ("WorkDate");

CREATE UNIQUE INDEX "IX_Departments_Name" ON "Departments" ("Name");

CREATE INDEX "IX_Employees_DepartmentId" ON "Employees" ("DepartmentId");

CREATE UNIQUE INDEX "IX_Employees_Email" ON "Employees" ("Email");

CREATE UNIQUE INDEX "IX_Employees_EmployeeCode" ON "Employees" ("EmployeeCode");

CREATE INDEX "IX_Employees_ManagerId" ON "Employees" ("ManagerId");

CREATE INDEX "IX_LeaveRequests_ApprovedById" ON "LeaveRequests" ("ApprovedById");

CREATE INDEX "IX_LeaveRequests_EmployeeId" ON "LeaveRequests" ("EmployeeId");

CREATE INDEX "IX_LeaveRequests_Status" ON "LeaveRequests" ("Status");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260812102505_InitialCreate', '8.0.30');

COMMIT;

